### ISSUE TITLE
Issue Launching CFN Version of QS.

### ISSUE THREAD

**Issue by troy-ameigh** [aws-quickstart/quickstart-aws-biotech-blueprint-cdk#26]
When Launching the CFN version of the QS, it states you do not need to add values for the Parameters in CFN console, however it appears that you do. 
<img width="881" alt="Screen Shot 2022-02-15 at 12 40 31 PM" src="https://user-images.githubusercontent.com/55170274/154129844-afe2768a-535b-46f4-b63c-c68fe235e181.png">
<img width="831" alt="Screen Shot 2022-02-15 at 12 47 17 PM" src="https://user-images.githubusercontent.com/55170274/154129856-494bae7d-ba23-4eed-9129-7d048cbc5e3d.png">

**Comment by troy-ameigh** [comment]
These have no default values in the template.

**Comment by troy-ameigh** [comment]
Here is the error, which is caused by the missing parameters.
![Screen Shot 2022-02-15 at 1 33 57 PM](https://user-images.githubusercontent.com/55170274/154136661-c6fad941-98f7-4f76-85a3-879d87060c43.png)

**Comment by paulu-aws** [comment]
This PR should resolve this. https://github.com/aws-quickstart/quickstart-aws-biotech-blueprint-cdk/pull/27
