### ISSUE TITLE
Issue deploying through CDK

### ISSUE THREAD

**Issue by keertirg** [aws-quickstart/quickstart-aws-biotech-blueprint-cdk#34]
When building through the CDK, we do see the below errors which can be reproduced with the recent source code changes.

ec2-user@ip-10-0-2-8 quickstart-aws-biotech-blueprint-cdk]$ npm run build

> aws-startup-blueprint@0.1.0 build
> npm run minify && tsc

> aws-startup-blueprint@0.1.0 minify
> jsmin -o scripts/config-enforcepermissionboundary.min.js scripts/config-enforcepermissionboundary.js

node_modules/@types/prettier/index.d.ts:41:54 - error TS2315: Type 'IsTuple' is not generic.

41 type IndexProperties<T extends { length: number }> = IsTuple<T> extends true
                                                        ~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:53:6 - error TS2456: Type alias 'IsTuple' circularly references itself.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
        ~~~~~~~

node_modules/@types/prettier/index.d.ts:53:65 - error TS2574: A rest element type must be an array type.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                   ~~~~~~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:53:84 - error TS2315: Type 'IsTuple' is not generic.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                                      ~~~~~~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:96:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

96     call<
       ~~~~

node_modules/@types/prettier/index.d.ts:131:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

131     each<
        ~~~~

node_modules/@types/prettier/index.d.ts:165:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

165     map<
        ~~~


Found 7 errors.

**Comment by paulu-aws** [comment]
Thanks for raising the issue @keertirg.

This pull request #36 addresses this. Hopefully, it will get merged into main quickly, but a simple version bump for typescript in the `package.json` to `"typescript": "~4.2.0",` and you should be on your way.

**Comment by sshvans** [comment]
PR has been merged.
